/* ═══ EXPORT ═══ */
async function _renderMermaidSVG(html){
  if(!html.includes('language-mermaid'))return html;
  await _ensureMermaid();
  if(!_mermaidReady)return html;
  try{mermaid.initialize({startOnLoad:false,theme:'default',securityLevel:'strict'});}catch(e){}
  const re=/<pre><code class="language-mermaid">([\s\S]*?)<\/code><\/pre>/g;
  let result=html;let idx=0;const matches=[];let m;
  while((m=re.exec(html))!==null)matches.push({full:m[0],code:m[1]});
  for(const match of matches){
    const code=match.code.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"');
    try{
      const {svg}=await mermaid.render('_pmm'+(idx++),code);
      result=result.replace(match.full,'<div style="text-align:center;margin:16px 0;page-break-inside:avoid;">'+svg+'</div>');
    }catch(e){}
  }
  try{_initMermaidTheme();}catch(e){}
  return result;
}
async function exportZIP(){
  const _ja=S.lang==='ja';
  if(window._noZip||typeof JSZip==='undefined'){exportConcatenatedFallback();return;}
  const zip=new JSZip();
  const root=fileSlug(S.projectName);
  Object.entries(S.files).forEach(([path,content])=>{
    zip.file(root+'/'+path,content);
  });
  const blob=await zip.generateAsync({type:'blob'});
  const url=URL.createObjectURL(blob);
  const link=document.createElement('a');link.href=url;link.download=root+'.zip';link.click();
  URL.revokeObjectURL(url);
  addMsg('bot',_ja?`📦 ${root}.zip (${Object.keys(S.files).length}ファイル) をダウンロードしました！`:`📦 Downloaded ${root}.zip (${Object.keys(S.files).length} files)!`);
  S._zipDone=true;
  _lsSet('devforge-last-export',new Date().toISOString());
}

async function exportPDF(){
  const _ja=S.lang==='ja';
  const G=S.genLang==='ja'||(!S.genLang&&_ja);
  let content='';
  for(const [path,text] of Object.entries(S.files)){
    if(path.endsWith('.md')){
      content+=`<h1 style="page-break-before:always;border-bottom:2px solid #3b82f6;padding-bottom:8px;margin-top:40px;">${escHtml(path)}</h1>`;
      const mdHtml=safeMD(text);
      content+=await _renderMermaidSVG(mdHtml);
    }
  }
  const pdfCss='body{font-family:-apple-system,sans-serif;padding:40px;max-width:800px;margin:0 auto;color:#1e222d;}'
    +'pre{background:#f5f5f5;padding:16px;border-radius:8px;overflow-x:auto;}'
    +'h1{margin-top:40px;}h1:first-child{page-break-before:avoid;}'
    +'table{width:100%;border-collapse:collapse;}th,td{border:1px solid #ddd;padding:8px;text-align:left;}th{background:#f0f0f0;}'
    +'div[style*="page-break-inside:avoid"] svg{max-width:100%;height:auto;}'
    +'@media print{body{padding:20px;}h1{page-break-before:always;}h1:first-child{page-break-before:avoid;}div[style*="page-break-inside:avoid"]{page-break-inside:avoid;}svg{max-width:100%;}}';
  const _CSP_META='<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data: blob:;">';
  const html=`<!DOCTYPE html><html><head>${_CSP_META}<title>${escHtml(S.projectName)} - DevForge v9</title><style>${pdfCss}
</style></head><body><div style="text-align:center;margin-bottom:40px;"><h1 style="page-break-before:avoid;border:none;font-size:24px;">${escHtml(S.projectName)}</h1><p style="color:#666;">Generated by DevForge v9 — ${new Date().toLocaleDateString(G?'ja-JP':'en-US')}</p><p style="color:#999;font-size:12px;">${G?'© 2026 エンジニアリングのタネ制作委員会 ｜ 作成者：にしあん':'© 2026 Engineering no Tane Committee | by にしあん'}</p></div>${content}</body></html>`;
  const win=window.open('','_blank');
  if(win){
    win.document.write(html);
    win.document.close();
    addMsg('bot',_ja?'📄 PDFプレビューを新しいタブで開きました。Ctrl+P で印刷/PDF保存できます。':'📄 PDF preview opened in new tab. Use Ctrl+P to print/save as PDF.');
  } else {
    // Fallback: download as HTML file
    const blob=new Blob([html],{type:'text/html'});
    const a=document.createElement('a');a.href=URL.createObjectURL(blob);
    a.download=fileSlug(S.projectName)+'-docs.html';a.click();URL.revokeObjectURL(a.href);
    addMsg('bot',_ja?'📄 ポップアップがブロックされたため、HTMLファイルとしてダウンロードしました。ブラウザで開いてCtrl+Pで印刷できます。':'📄 Popup blocked. Downloaded as HTML. Open in browser and use Ctrl+P to print.');
  }
}

function copyAllFiles(){
  const _ja=S.lang==='ja';
  const sep='\n\n'+'='.repeat(60)+'\n';
  const all=Object.entries(S.files).map(([path,content])=>`${sep}📄 ${path}${sep}${content}`).join('\n');
  const header=`# ${S.projectName} — ${_ja?'全ファイル結合':'All Files Combined'}\n# Generated by DevForge v9\n# Files: ${Object.keys(S.files).length}\n# Date: ${new Date().toISOString().split('T')[0]}`;
  const fullText=header+'\n'+all;
  if(navigator.clipboard&&navigator.clipboard.writeText){
    navigator.clipboard.writeText(fullText).then(()=>{
      toast(_ja?`📋 全${Object.keys(S.files).length}ファイルをコピーしました`:`📋 Copied all ${Object.keys(S.files).length} files`);
      addMsg('bot',_ja?`📋 全${Object.keys(S.files).length}ファイルをクリップボードにコピーしました。AIへの一括投入にご利用ください。`:`📋 Copied all ${Object.keys(S.files).length} files to clipboard.`);
    }).catch(()=>{_fallbackCopy(fullText);toast(_ja?'📋 コピーしました':'📋 Copied');});
  } else {_fallbackCopy(fullText);toast(_ja?'📋 コピーしました':'📋 Copied');}
}

async function exportSelectedZip(paths){
  const _ja=S.lang==='ja';
  if(window._noZip||typeof JSZip==='undefined'){toast(_ja?'⚠️ ZIPエクスポートを利用できません':'⚠️ ZIP export unavailable');return;}
  if(!paths||!paths.length){toast(_ja?'⚠️ 対象ファイルが見つかりません':'⚠️ No matching files found');return;}
  const zip=new JSZip();
  const root=fileSlug(S.projectName);
  paths.forEach(function(p){if(S.files[p])zip.file(root+'/'+p,S.files[p]);});
  const blob=await zip.generateAsync({type:'blob'});
  const url=URL.createObjectURL(blob);
  const link=document.createElement('a');link.href=url;link.download=root+'-selected.zip';link.click();
  URL.revokeObjectURL(url);
  toast(_ja?'📦 '+paths.length+'ファイルをエクスポートしました':'📦 Exported '+paths.length+' files');
}

function exportPillarGroup(prefixCsv){
  const prefs=prefixCsv.split(',');
  const paths=Object.keys(S.files).filter(function(f){return prefs.some(function(pr){return f.startsWith(pr)||f.includes(pr);});});
  exportSelectedZip(paths);
}

function copyForAI(){
  const _ja=S.lang==='ja';
  const files=Object.entries(S.files);
  const tokens=Math.round(files.reduce((s,[,c])=>s+c.length,0)/4);
  let md=`# ${S.projectName}\n\n`;
  md+=`> ${_ja?'DevForge v9 で生成':'Generated by DevForge v9'} | ${files.length} ${_ja?'ファイル':'files'} | ~${tokens.toLocaleString()} tokens\n\n`;
  md+='## Table of Contents\n\n';
  files.forEach(([p],i)=>{md+=`${i+1}. \`${p}\`\n`;});
  md+='\n---\n\n';
  files.forEach(([path,content])=>{
    md+=`## ${path}\n\n\`\`\`${path.split('.').pop()}\n${content}\n\`\`\`\n\n`;
  });
  if(navigator.clipboard&&navigator.clipboard.writeText){
    navigator.clipboard.writeText(md).then(()=>{
      toast(_ja?`🤖 AI向けMarkdown (${files.length}ファイル) をコピー`:`🤖 Copied AI Markdown (${files.length} files)`);
    }).catch(()=>{_fallbackCopy(md);toast(_ja?'📋 コピーしました':'📋 Copied');});
  } else {_fallbackCopy(md);toast(_ja?'📋 コピーしました':'📋 Copied');}
}

/* ═══ ANSWERS JSON EXPORT / IMPORT ═══ */

function exportAnswersJSON(){
  const _ja=S.lang==='ja';
  const data={
    _devforge:'answers-v1',
    _version:9,
    projectName:S.projectName||'',
    preset:S.preset||'custom',
    lang:S.lang||'ja',
    genLang:S.genLang||'ja',
    skillLv:typeof S.skillLv==='number'?S.skillLv:0,
    answers:Object.assign({},S.answers),
  };
  const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});
  const url=URL.createObjectURL(blob);
  const a=document.createElement('a');a.href=url;
  a.download=(fileSlug(S.projectName)||'devforge')+'.answers.json';
  a.click();URL.revokeObjectURL(url);
  toast(_ja?'💾 回答をJSONで保存しました':'💾 Answers saved as JSON');
}

function importAnswersJSON(){
  const _ja=S.lang==='ja';
  const inp=document.createElement('input');inp.type='file';inp.accept='.json';
  inp.onchange=function(e){
    const f=e.target.files[0];if(!f)return;
    const reader=new FileReader();
    reader.onload=function(ev){
      try{
        const data=_jp(ev.target.result,null);
        if(!data||data._devforge!=='answers-v1'){toast(_ja?'❌ 無効なファイル形式です（.answers.json が必要）':'❌ Invalid format (need .answers.json)');return;}
        if(data.projectName)S.projectName=sanitizeName(data.projectName);
        if(typeof data.preset==='string')S.preset=sanitize(data.preset,100);
        if(data.lang==='ja'||data.lang==='en')S.lang=data.lang;
        if(data.genLang==='ja'||data.genLang==='en')S.genLang=data.genLang;
        if(typeof data.skillLv==='number'&&data.skillLv>=0&&data.skillLv<=6){
          S.skillLv=data.skillLv;
          if(typeof skillTier==='function')S.skill=skillTier(data.skillLv);
        }
        if(data.answers&&typeof data.answers==='object'&&!Array.isArray(data.answers)){
          const ans={};
          Object.keys(data.answers).forEach(function(k){
            if(['__proto__','constructor','prototype'].includes(k))return;
            const v=data.answers[k];
            if(typeof v==='string')ans[k]=sanitize(v,500);
            else if(Array.isArray(v))ans[k]=v.filter(function(x){return typeof x==='string';}).map(function(x){return sanitize(x,200);});
          });
          S.answers=ans;
        }
        save();
        toast(_ja?'✅ 回答を読み込みました — ウィザードで確認してください':'✅ Answers imported — review in wizard');
        S.phase=1;S.step=0;save();
        if(typeof renderWizard==='function')renderWizard();
      }catch(err){
        toast(_ja?'❌ 読み込みに失敗しました':'❌ Import failed');
      }
    };
    reader.readAsText(f);
  };
  inp.click();
}

/* ═══ OFFLINE FALLBACK ═══ */
function exportConcatenatedFallback(){
  const _ja=S.lang==='ja';
  var content='# '+S.projectName+' — '+(_ja?'全ファイル結合':'All Files Combined')+'\n';
  content+='# Generated by DevForge v9 | '+Object.keys(S.files).length+' files\n\n';
  Object.entries(S.files).forEach(function(e){
    content+='# === FILE: '+e[0]+' ===\n\n'+e[1]+'\n\n';
  });
  var blob=new Blob([content],{type:'text/markdown'});
  var url=URL.createObjectURL(blob);
  var link=document.createElement('a');link.href=url;link.download=fileSlug(S.projectName)+'-all-files.md';
  link.click();URL.revokeObjectURL(url);
  toast(_ja?'📄 全ファイルをMDとして保存しました（ZIPライブラリ未取得のフォールバック）':'📄 Saved all files as .md (ZIP fallback — JSZip unavailable)');
  if(typeof addMsg==='function')addMsg('bot',_ja?
    '📄 JSZipが読み込まれていないため、全ファイルを結合MDファイルとして保存しました。オンライン環境でのZIPダウンロードもお試しください。':
    '📄 JSZip unavailable — saved all files as combined .md. Try ZIP download with an internet connection.');
}

/* ═══ ROLE-BASED EXPORT ═══ */
var EXPORT_ROLES={
  developer:{ja:'👨‍💻 開発者',en:'👨‍💻 Developer',
    prefixes:['CLAUDE.md','.spec/','.cursorrules','.clinerules','.windsurfrules','docs/03_','docs/06_','docs/07_','docs/22_','docs/82_','.devcontainer/','.github/','scaffolding/'],
    priority:['CLAUDE.md','.spec/specification.md','.spec/technical-plan.md','.spec/tasks.md','docs/03_architecture.md','docs/06_api_design.md','docs/07_db_design.md','docs/22_security.md','scaffolding/SETUP.md','.cursorrules'],
  },
  pm:{ja:'📋 PM',en:'📋 PM',
    prefixes:['docs/01_','docs/02_','docs/05_','docs/14_','docs/09_','docs/15_','docs/107_','docs/24_','.spec/tasks.md'],
    priority:['docs/01_project_overview.md','docs/02_requirements.md','docs/05_roadmap.md','docs/14_risk_management.md','docs/107_project_governance.md','docs/108_uat_acceptance.md','docs/09_release_checklist.md','.spec/tasks.md'],
  },
  qa:{ja:'🧪 QA',en:'🧪 QA',
    prefixes:['docs/17_','docs/18_','docs/19_','docs/22_','docs/108_','docs/33_','docs/20_'],
    priority:['docs/108_uat_acceptance.md','docs/17_test_strategy.md','docs/18_test_plan.md','docs/22_security.md','docs/33_test_matrix.md','docs/20_a11y.md'],
  },
  designer:{ja:'🎨 デザイナー',en:'🎨 Designer',
    prefixes:['docs/10_','docs/11_','docs/20_','docs/02_'],
    priority:['docs/10_design_system.md','docs/11_ui_components.md','docs/20_a11y.md','docs/02_requirements.md'],
  },
  ai:{ja:'🤖 AI投入用',en:'🤖 AI Context',
    prefixes:['CLAUDE.md','AI_BRIEF.md','AGENTS.md','.cursorrules','.clinerules','.windsurfrules','.codex/','.spec/','skills/','docs/115_'],
    priority:['CLAUDE.md','AI_BRIEF.md','AGENTS.md','.spec/constitution.md','.spec/specification.md','.spec/tasks.md','.cursorrules','docs/113_ai_collaboration_guide.md'],
  },
};

function exportByRole(role){
  const _ja=S.lang==='ja';
  var r=EXPORT_ROLES[role];if(!r)return;
  var paths=Object.keys(S.files).filter(function(f){
    return r.prefixes.some(function(pr){return f===pr||f.startsWith(pr);});
  });
  if(!paths.length){toast(_ja?'⚠️ 対象ファイルが見つかりません':'⚠️ No files found for this role');return;}
  exportSelectedZip(paths);
}

function showPMRole(role){
  const _ja=S.lang==='ja';
  var r=EXPORT_ROLES[role];if(!r)return;
  document.querySelectorAll('.pm-tab').forEach(function(t){
    t.classList.toggle('pm-tab-active',t.dataset.role===role);
  });
  var existing=r.priority.filter(function(f){
    return S.files[f]||Object.keys(S.files).some(function(k){return k.startsWith(f);});
  });
  var el=$('pmFiles');if(!el)return;
  el.innerHTML=existing.map(function(f){
    var disp=f.replace(/^\.spec\//,'').replace(/^docs\//,'').replace(/^\.cursorrules$/,'.cursorrules');
    return '<div class="pm-file" onclick="previewFile(\''+escAttr(f)+'\')" role="button" tabindex="0">'+
      '<span class="pm-file-name">'+esc(disp)+'</span>'+
      '<span class="pm-file-arr">→</span></div>';
  }).join('')||('<div class="pm-empty">'+(_ja?'このプロジェクトには対象ファイルがありません':'No matching files for this project')+'</div>');
  var btn=$('pmDlBtn');
  if(btn)btn.setAttribute('onclick','exportByRole(\''+escAttr(role)+'\')');
}

/* ═══ UI HELPERS ═══ */

