/* ═══ EXPORT ═══ */
async function _renderMermaidSVG(html){
  if(!html.includes('language-mermaid'))return html;
  await _ensureMermaid();
  if(!_mermaidReady)return html;
  try{mermaid.initialize({startOnLoad:false,theme:'default',securityLevel:'strict'});}catch(e){}
  const re=/<pre><code class="language-mermaid">([\s\S]*?)<\/code><\/pre>/g;
  let result=html;let idx=0;const matches=[];let m;
  while((m=re.exec(html))!==null)matches.push({full:m[0],code:m[1]});
  for(const match of matches){
    const code=match.code.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"');
    try{
      const {svg}=await mermaid.render('_pmm'+(idx++),code);
      result=result.replace(match.full,'<div style="text-align:center;margin:16px 0;page-break-inside:avoid;">'+svg+'</div>');
    }catch(e){}
  }
  try{_initMermaidTheme();}catch(e){}
  return result;
}
async function exportZIP(){
  const _ja=S.lang==='ja';
  if(window._noZip||typeof JSZip==='undefined'){toast(_ja?'⚠️ オフライン環境ではZIPエクスポートを利用できません':'⚠️ ZIP export unavailable offline');return;}
  const zip=new JSZip();
  const root=fileSlug(S.projectName);
  Object.entries(S.files).forEach(([path,content])=>{
    zip.file(root+'/'+path,content);
  });
  const blob=await zip.generateAsync({type:'blob'});
  const url=URL.createObjectURL(blob);
  const link=document.createElement('a');link.href=url;link.download=root+'.zip';link.click();
  URL.revokeObjectURL(url);
  addMsg('bot',_ja?`📦 ${root}.zip (${Object.keys(S.files).length}ファイル) をダウンロードしました！`:`📦 Downloaded ${root}.zip (${Object.keys(S.files).length} files)!`);
  _lsSet('devforge-last-export',new Date().toISOString());
}

async function exportPDF(){
  const _ja=S.lang==='ja';
  const G=S.genLang==='ja'||(!S.genLang&&_ja);
  let content='';
  for(const [path,text] of Object.entries(S.files)){
    if(path.endsWith('.md')){
      content+=`<h1 style="page-break-before:always;border-bottom:2px solid #3b82f6;padding-bottom:8px;margin-top:40px;">${escHtml(path)}</h1>`;
      const mdHtml=safeMD(text);
      content+=await _renderMermaidSVG(mdHtml);
    }
  }
  const pdfCss='body{font-family:-apple-system,sans-serif;padding:40px;max-width:800px;margin:0 auto;color:#1e222d;}'
    +'pre{background:#f5f5f5;padding:16px;border-radius:8px;overflow-x:auto;}'
    +'h1{margin-top:40px;}h1:first-child{page-break-before:avoid;}'
    +'table{width:100%;border-collapse:collapse;}th,td{border:1px solid #ddd;padding:8px;text-align:left;}th{background:#f0f0f0;}'
    +'div[style*="page-break-inside:avoid"] svg{max-width:100%;height:auto;}'
    +'@media print{body{padding:20px;}h1{page-break-before:always;}h1:first-child{page-break-before:avoid;}div[style*="page-break-inside:avoid"]{page-break-inside:avoid;}svg{max-width:100%;}}';
  const _CSP_META='<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data: blob:;">';
  const html=`<!DOCTYPE html><html><head>${_CSP_META}<title>${escHtml(S.projectName)} - DevForge v9</title><style>${pdfCss}
</style></head><body><div style="text-align:center;margin-bottom:40px;"><h1 style="page-break-before:avoid;border:none;font-size:24px;">${escHtml(S.projectName)}</h1><p style="color:#666;">Generated by DevForge v9 — ${new Date().toLocaleDateString(G?'ja-JP':'en-US')}</p><p style="color:#999;font-size:12px;">${G?'© 2026 エンジニアリングのタネ制作委員会 ｜ 作成者：にしあん':'© 2026 Engineering no Tane Committee | by にしあん'}</p></div>${content}</body></html>`;
  const win=window.open('','_blank');
  if(win){
    win.document.write(html);
    win.document.close();
    addMsg('bot',_ja?'📄 PDFプレビューを新しいタブで開きました。Ctrl+P で印刷/PDF保存できます。':'📄 PDF preview opened in new tab. Use Ctrl+P to print/save as PDF.');
  } else {
    // Fallback: download as HTML file
    const blob=new Blob([html],{type:'text/html'});
    const a=document.createElement('a');a.href=URL.createObjectURL(blob);
    a.download=fileSlug(S.projectName)+'-docs.html';a.click();URL.revokeObjectURL(a.href);
    addMsg('bot',_ja?'📄 ポップアップがブロックされたため、HTMLファイルとしてダウンロードしました。ブラウザで開いてCtrl+Pで印刷できます。':'📄 Popup blocked. Downloaded as HTML. Open in browser and use Ctrl+P to print.');
  }
}

function copyAllFiles(){
  const _ja=S.lang==='ja';
  const sep='\n\n'+'='.repeat(60)+'\n';
  const all=Object.entries(S.files).map(([path,content])=>`${sep}📄 ${path}${sep}${content}`).join('\n');
  const header=`# ${S.projectName} — ${_ja?'全ファイル結合':'All Files Combined'}\n# Generated by DevForge v9\n# Files: ${Object.keys(S.files).length}\n# Date: ${new Date().toISOString().split('T')[0]}`;
  const fullText=header+'\n'+all;
  if(navigator.clipboard&&navigator.clipboard.writeText){
    navigator.clipboard.writeText(fullText).then(()=>{
      toast(_ja?`📋 全${Object.keys(S.files).length}ファイルをコピーしました`:`📋 Copied all ${Object.keys(S.files).length} files`);
      addMsg('bot',_ja?`📋 全${Object.keys(S.files).length}ファイルをクリップボードにコピーしました。AIへの一括投入にご利用ください。`:`📋 Copied all ${Object.keys(S.files).length} files to clipboard.`);
    }).catch(()=>{_fallbackCopy(fullText);toast(_ja?'📋 コピーしました':'📋 Copied');});
  } else {_fallbackCopy(fullText);toast(_ja?'📋 コピーしました':'📋 Copied');}
}

function copyForAI(){
  const _ja=S.lang==='ja';
  const files=Object.entries(S.files);
  const tokens=Math.round(files.reduce((s,[,c])=>s+c.length,0)/4);
  let md=`# ${S.projectName}\n\n`;
  md+=`> ${_ja?'DevForge v9 で生成':'Generated by DevForge v9'} | ${files.length} ${_ja?'ファイル':'files'} | ~${tokens.toLocaleString()} tokens\n\n`;
  md+='## Table of Contents\n\n';
  files.forEach(([p],i)=>{md+=`${i+1}. \`${p}\`\n`;});
  md+='\n---\n\n';
  files.forEach(([path,content])=>{
    md+=`## ${path}\n\n\`\`\`${path.split('.').pop()}\n${content}\n\`\`\`\n\n`;
  });
  if(navigator.clipboard&&navigator.clipboard.writeText){
    navigator.clipboard.writeText(md).then(()=>{
      toast(_ja?`🤖 AI向けMarkdown (${files.length}ファイル) をコピー`:`🤖 Copied AI Markdown (${files.length} files)`);
    }).catch(()=>{_fallbackCopy(md);toast(_ja?'📋 コピーしました':'📋 Copied');});
  } else {_fallbackCopy(md);toast(_ja?'📋 コピーしました':'📋 Copied');}
}

/* ═══ UI HELPERS ═══ */

