/* ── Pillar ① SDD Integration (Phase B: Context-Aware) ── */
function genPillar1_SDD(a,pn){
  const G=S.genLang==='ja';
  const date=new Date().toISOString().split('T')[0];
  const fe=a.frontend||'React + Next.js';
  const be=a.backend||'Node.js + Express';
  const db=a.database||'PostgreSQL';
  const methods=(a.dev_methods||'TDD').split(', ');
  const auth=resolveAuth(a);
  const arch=resolveArch(a);
  const sched=buildSchedule(a);

  // B4: scope_out auto-adjustment + G3: domain inference
  let scopeOut=a.scope_out || (()=>{
    const domain=detectDomain(a.purpose);
    const defaults={
      education: G?'ネイティブアプリ, 動画配信インフラ, 決済以外の金融機能':'Native apps, Video streaming infrastructure, Non-payment financial features',
      ec: G?'ネイティブアプリ, 実店舗POS連携, 会計ソフト連携, 物流管理':'Native apps, POS integration, Accounting software, Logistics management',
      community: G?'ネイティブアプリ, 動画配信, リアルタイムビデオ通話, メール配信':'Native apps, Video streaming, Real-time video calls, Email delivery',
      saas: G?'ネイティブアプリ, オンプレミスデプロイ, ホワイトラベル対応':'Native apps, On-premise deployment, White-label support',
      content: G?'ネイティブアプリ, 動画配信, コメント通知メール':'Native apps, Video streaming, Comment notification emails',
      analytics: G?'ネイティブアプリ, ETLパイプライン構築, データウェアハウス':'Native apps, ETL pipeline, Data warehouse',
      booking: G?'ネイティブアプリ, 決済代行, カレンダー同期(外部API)':'Native apps, Payment processing, Calendar sync (external API)',
      marketplace: G?'ネイティブアプリ, 物流管理, エスクロー決済':'Native apps, Logistics management, Escrow payments',
    };
    return defaults[domain] || (G?'ネイティブアプリ, モバイルアプリ':'Native apps, Mobile apps');
  })();
  if(a.mobile&&!isNone(a.mobile)&&!String(a.mobile).includes('PWA')){
    scopeOut=scopeOut.replace(/ネイティブアプリ/g,G?'ストア配布用ネイティブビルド（Expo Web UIは対象内）':'Native app store builds (Expo Web UI is in scope)');
    scopeOut=scopeOut.replace(/native apps?/gi,'Native app store builds (Expo Web UI is in scope)');
  }

  // Auth detail lines
  const authLines=['- '+(G?'認証SoT（Source of Truth）':'Auth SoT')+': '+auth.sot,
    '- '+(G?'トークン形式':'Token Type')+': '+auth.tokenType,
    '- '+(G?'トークン検証':'Token Verification')+': '+auth.tokenVerify];
  if(auth.social.length) authLines.push('- '+(G?'ソーシャルログイン':'Social Login')+': '+auth.social.join(', '));
  authLines.push('- '+(G?'HTTPS必須':'HTTPS required'),'- '+(G?'環境変数でシークレット管理':'Secrets via env vars'),'- '+(G?'SQLインジェクション・XSS対策':'SQL injection & XSS prevention'));

  // Architecture label
  const archLabel=G?{baas:'BaaS統合型',bff:'BFF（API Routes統合）',split:'FE/BE分離型',traditional:'従来型クライアント-サーバー'}[arch.pattern]:{baas:'BaaS Integration',bff:'BFF (API Routes)',split:'FE/BE Split',traditional:'Traditional Client-Server'}[arch.pattern];

  // ════ Constitution ════
  S.files['.spec/constitution.md']=[
    '# '+pn+' — '+(G?'プロジェクト憲法 (Constitution)':'Project Constitution'),
    '> Generated by DevForge v9 — '+date,'',
    G?'## 1. プロジェクトの使命':'## 1. Mission',a.purpose||(G?'（未定義）':'(Undefined)'),'',
    G?'## 2. ターゲットユーザー':'## 2. Target Users',a.target||(G?'（未定義）':'(Undefined)'),'',
    G?'## 3. 成功指標':'## 3. Success Metrics',
    a.success || (()=>{
      const domain=detectDomain(a.purpose);
      const kpis={
        education: G?'- コース完了率: 70%以上\n- 月間アクティブ学習者数 (MAL): 前月比+10%\n- 学習者満足度 (NPS): 40以上':'- Course completion rate: 70%+\n- Monthly Active Learners (MAL): +10% MoM\n- Learner NPS: 40+',
        ec: G?'- 月間GMV: 前月比+15%\n- 購入CVR: 3%以上\n- カート離脱率: 70%以下':'- Monthly GMV: +15% MoM\n- Purchase CVR: 3%+\n- Cart abandonment: <70%',
        community: G?'- 月間アクティブユーザー (MAU): 前月比+10%\n- 投稿/コメント率: DAU対比30%以上\n- 7日リテンション率: 40%以上':'- Monthly Active Users (MAU): +10% MoM\n- Post/comment rate: 30%+ of DAU\n- 7-day retention: 40%+',
        saas: G?'- MRR（月次経常収益）: 前月比+10%\n- チャーン率: 月5%以下\n- NPS: 40以上':'- MRR: +10% MoM\n- Monthly churn: <5%\n- NPS: 40+',
        content: G?'- 月間PV: 前月比+20%\n- 平均滞在時間: 3分以上\n- リピート訪問率: 30%以上':'- Monthly PV: +20% MoM\n- Avg session: 3min+\n- Return visit rate: 30%+',
        analytics: G?'- DAU: 前月比+10%\n- レポート生成数: 週10件以上/ユーザー\n- データ更新頻度: リアルタイム(< 1分)':'- DAU: +10% MoM\n- Reports generated: 10+/week/user\n- Data refresh: real-time (<1min)',
        booking: G?'- 予約完了率: 80%以上\n- 月間予約件数: 前月比+15%\n- キャンセル率: 10%以下':'- Booking completion: 80%+\n- Monthly bookings: +15% MoM\n- Cancellation rate: <10%',
        marketplace: G?'- 月間取引件数: 前月比+15%\n- 出品者定着率: 60%以上\n- 購入者CVR: 5%以上':'- Monthly transactions: +15% MoM\n- Seller retention: 60%+\n- Buyer CVR: 5%+',
      };
      return kpis[domain] || (G?'- テストカバレッジ: 80%以上\n- ユーザー満足度: NPS 40以上\n- p95レスポンスタイム: 500ms以下':'- Test coverage: 80%+\n- User satisfaction: NPS 40+\n- p95 response time: <500ms');
    })(),'',
    G?'## 4. 技術原則':'## 4. Tech Principles',
    '- '+(G?'フロントエンド':'Frontend')+': '+fe,
    '- '+(G?'バックエンド':'Backend')+': '+be,
    '- '+(G?'データベース':'Database')+': '+db,
    '- '+(G?'アーキテクチャ':'Architecture')+': '+archLabel,
    '- '+(G?'駆動開発手法':'Dev Methods')+': '+methods.join(', '),'',
    G?'## 5. 品質基準':'## 5. Quality Standards',
    '- '+(G?'テストカバレッジ: 80%以上':'Test Coverage: 80%+'),
    '- TypeScript strict mode',
    '- ESLint + Prettier '+(G?'適用':'enforced'),
    '- CI/CD '+(G?'パイプライン必須':'pipeline required'),'',
    G?'## 6. セキュリティ方針':'## 6. Security Policy',...authLines,'',
    G?'## 7. スコープ外':'## 7. Out of Scope',scopeOut,''
  ].join('\n');

  // B1: Architecture-aware API design
  let apiDesignLines;
  if(arch.isBaaS){
    const bn=be.includes('Supabase')?'Supabase':be.includes('Firebase')?'Firebase':'Convex';
    const rt=be.includes('Supabase')?'Supabase Realtime (WebSocket)':be.includes('Firebase')?'Firestore onSnapshot':'Convex Subscriptions';
    const fn=be.includes('Supabase')?'Supabase Edge Functions (Deno)':be.includes('Firebase')?'Cloud Functions':'Convex Functions';
    apiDesignLines=['- '+(G?'アクセス方式':'Access')+': '+bn+' Client SDK','- '+(G?'認証':'Auth')+': '+auth.tokenType,'- '+(G?'リアルタイム':'Realtime')+': '+rt,'- '+(G?'サーバーサイドロジック':'Server Logic')+': '+fn];
  } else if(arch.pattern==='bff'){
    apiDesignLines=['- RESTful API (Next.js API Routes / Route Handlers)','- '+(G?'バージョニング':'Versioning')+': /api/v1/','- '+(G?'認証':'Auth')+': '+auth.tokenType,'- '+(G?'レスポンス':'Response')+': JSON','- '+(G?'注意':'Note')+': '+(G?'Express のロジックは Next.js API Routes に統合。別途 Express サーバーは不要':'Express logic integrated into Next.js API Routes. No separate Express server needed.')];
  } else {
    apiDesignLines=['- RESTful API (OpenAPI 3.0)','- '+(G?'バージョニング':'Versioning')+': /api/v1/','- '+(G?'認証':'Auth')+': '+auth.tokenType,'- '+(G?'レスポンス':'Response')+': JSON'];
  }

  const hasMob=a.mobile&&!isNone(a.mobile);
  const hasPay=a.payment&&!isNone(a.payment);

  // ════ Specification ════
  const specLines=[
    '# '+pn+' — '+(G?'要件仕様書 (Specification)':'Specification'),
    '> Generated by DevForge v9 — '+date,'',
    G?'## 1. 機能要件':'## 1. Functional Requirements','',
    G?'### 1.1 MVP機能':'### 1.1 MVP Features',
    ...(a.mvp_features||'').split(', ').flatMap(f=>{
      const fd=getFeatureDetail(f);
      const lines=['#### '+f.trim()];
      if(fd){
        const criteria=G?fd.criteria_ja:fd.criteria_en;
        lines.push((G?'**受入条件:**':'**Acceptance Criteria:**'));
        criteria.forEach(c=>{
          const expanded=c.replace(/\{auth\}/g,a.auth||'OAuth');
          lines.push('- [ ] '+expanded);
        });
      } else {
        lines.push('- [ ] '+(G?'CRUD実装':'CRUD implementation'));
        lines.push('- [ ] '+(G?'バリデーション':'Validation'));
        lines.push('- [ ] '+(G?'権限チェック':'Authorization check'));
      }
      lines.push('');
      return lines;
    }),
    G?'### 1.2 主要画面':'### 1.2 Key Screens',
    (a.screens||'').split(', ').map(s=>'- '+s).join('\n'),'',
    G?'### 1.3 ルーティング':'### 1.3 Routing',
    '| URL | '+(G?'画面名':'Screen')+' | '+(G?'認証':'Auth')+' |',
    '|-----|------|------|',
    ...genRoutes(a).map(r=>'| `'+r.path+'` | '+r.name+' | '+(r.auth?(G?'🔒 要':'🔒 Yes'):(G?'🌐 公開':'🌐 Public'))+' |'),
    '',
    G?'### 1.4 データモデル':'### 1.4 Data Model','```',
    (G?'エンティティ':'Entities')+': '+(a.data_entities||(G?'（未定義）':'(Undefined)')),'```','',
    G?'## 2. 非機能要件':'## 2. Non-functional Requirements',
    '- '+(G?'レスポンスタイム':'Response Time')+': '+(S.skill==='pro'?'< 200ms (p95)':S.skill==='intermediate'?'< 500ms (p95)':'< 1000ms (p95)'),
    '- '+(G?'可用性':'Availability')+': '+(S.skill==='pro'?'99.9%':S.skill==='intermediate'?'99%':(G?'ベストエフォート（PaaS依存）':'Best effort (PaaS-dependent)')),
    '- '+(G?'同時接続':'Concurrent Users')+': '+(S.skill==='pro'?'1000+':S.skill==='intermediate'?'〜200':'〜50'),
    '- '+(G?'モバイル対応':'Mobile')+': '+(hasMob?'✅ '+a.mobile:(G?'レスポンシブWebのみ':'Responsive Web only')),'',
    G?'## 3. 技術スタック':'## 3. Tech Stack',
    '| '+(G?'レイヤー':'Layer')+' | '+(G?'技術':'Tech')+' |','|---------|------|',
    '| '+(G?'フロントエンド':'Frontend')+' | '+fe+' |',
    '| '+(G?'バックエンド':'Backend')+' | '+be+' |',
    '| '+(G?'データベース':'Database')+' | '+db+' |',
    '| '+(G?'認証SoT':'Auth SoT')+' | '+auth.sot+' |',
    '| '+(G?'デプロイ':'Deploy')+' | '+(a.deploy||'Vercel')+' |',
  ];
  if(hasMob) specLines.push('| '+(G?'モバイル':'Mobile')+' | '+a.mobile+' |');
  if(hasPay) specLines.push('| '+(G?'決済':'Payment')+' | '+a.payment+' |');
  specLines.push('',G?'## 4. API設計方針':'## 4. API Design',...apiDesignLines,'');

  // Stripe integration design
  if(hasPay&&(a.payment||'').includes('Stripe')){
    const isEdge=arch.isBaaS&&be.includes('Supabase');
    specLines.push(
      G?'## 5. 決済設計 (Stripe)':'## 5. Payment Design (Stripe)','',
      G?'### 5.1 プラン設計':'### 5.1 Plan Design',
      '| '+(G?'プラン':'Plan')+' | '+(G?'価格':'Price')+' | '+(G?'制限':'Limits')+' |',
      '|--------|-------|------|',
      '| Free | ¥0 | '+(G?'基本機能のみ':'Basic features only')+' |',
      '| Pro | ¥980/'+(G?'月':'mo')+' | '+(G?'全機能・優先サポート':'All features, priority support')+' |',
      '| Enterprise | ¥9,800/'+(G?'月':'mo')+' | '+(G?'全機能+SLA+専用サポート':'All features + SLA + dedicated support')+' |','',
      G?'### 5.2 決済フロー':'### 5.2 Payment Flow',
      '```',
      G?'1. ユーザーがプラン選択':'1. User selects plan',
      G?'2. Stripe Checkout セッション作成':'2. Create Stripe Checkout session',
      G?'3. Stripe決済画面にリダイレクト':'3. Redirect to Stripe payment page',
      G?'4. 決済完了 → success_url にリダイレクト':'4. Payment complete → redirect to success_url',
      G?'5. Webhook (invoice.paid) → DB更新':'5. Webhook (invoice.paid) → update DB',
      '```','',
      G?'### 5.3 Webhookイベント':'### 5.3 Webhook Events',
      '| Event | '+(G?'処理':'Action')+' |',
      '|-------|------|',
      '| `checkout.session.completed` | '+(G?'サブスクリプション開始':'Start subscription')+' |',
      '| `invoice.paid` | '+(G?'支払確認・期間更新':'Confirm payment, renew period')+' |',
      '| `customer.subscription.updated` | '+(G?'プラン変更反映':'Apply plan change')+' |',
      '| `customer.subscription.deleted` | '+(G?'解約処理':'Cancel subscription')+' |','',
      G?'### 5.4 実装':'### 5.4 Implementation',
      '- Endpoint: `/api/webhook/stripe`',
      '- '+(G?'署名検証':'Signature verification')+': `stripe.webhooks.constructEvent()`',
      '- '+(G?'冪等性':'Idempotency')+': event.id '+(G?'でDB重複チェック':'DB dedup check'),
      '- '+(G?'顧客紐付':'Customer mapping')+': User.stripe_customer_id','',
    );
  }

  // RBAC design
  const hasAdmin=/管理者|admin/i.test(a.target||'');
  if(hasAdmin){
    const rbacSectionNum=hasPay&&(a.payment||'').includes('Stripe')?6:5;
    specLines.push(
      (G?'## '+rbacSectionNum+'. ロール・権限設計 (RBAC)':'## '+rbacSectionNum+'. Role & Permission Design (RBAC)'),'',
      G?'### ロール定義':'### Role Definitions',
      '| '+(G?'ロール':'Role')+' | '+(G?'説明':'Description')+' | '+(G?'権限':'Permissions')+' |',
      '|--------|------|------|',
      '| user | '+(G?'一般ユーザー':'Regular user')+' | '+(G?'自分のデータのCRUD':'Own data CRUD')+' |',
      '| admin | '+(G?'管理者':'Administrator')+' | '+(G?'全データの閲覧・編集・ユーザー管理':'All data view/edit, user management')+' |',
      '| super_admin | '+(G?'スーパー管理者':'Super admin')+' | '+(G?'システム設定・ロール変更':'System config, role changes')+' |','',
      G?'### 権限チェック':'### Permission Check',
      '- profiles.role '+(G?'カラムでロール管理':'column for role management'),
      '- '+(G?'ミドルウェア':'Middleware')+': '+(arch.isBaaS?'RLS + auth.jwt() role check':(G?'API Middleware で role チェック':'API middleware role check')),
      '- '+(G?'管理者ルート':'Admin routes')+': /admin/ → role=admin '+(G?'以上':'or above'),
      '- '+(G?'監査ログ':'Audit log')+': '+(G?'管理者操作は全件記録':'Log all admin actions'),'',
    );
  }

  S.files['.spec/specification.md']=specLines.join('\n');

  // Directory structure adapts to architecture
  const dirLines=[pn+'/',
    '├── src/',
    '│   ├── app/          # '+(G?'ページ・ルーティング':'Pages & routing'),
    '│   ├── components/   # '+(G?'UIコンポーネント':'UI components'),
    '│   ├── lib/          # '+(G?'ユーティリティ':'Utilities'),
    '│   ├── hooks/        # '+(G?'カスタムフック':'Custom hooks'),
    '│   └── types/        # '+(G?'TypeScript型定義':'TypeScript types')];
  if(arch.isBaaS){
    if(be.includes('Supabase')) dirLines.push('├── supabase/         # '+(G?'マイグレーション・Edge Functions':'Migrations & Edge Functions'));
    else if(be.includes('Firebase')) dirLines.push('├── functions/        # '+(G?'Cloud Functions':'Cloud Functions'));
  } else {
    if(arch.pattern!=='bff') dirLines.push('├── api/              # '+(G?'バックエンドAPI':'Backend API'));
    const ormN=(a.orm&&a.orm.includes('Drizzle'))?'drizzle':'prisma';
    dirLines.push('├── '+ormN+'/           # '+(G?'スキーマ・マイグレーション':'Schema & migrations'));
  }
  dirLines.push('├── tests/            # '+(G?'テスト':'Tests'),
    '├── .spec/            # '+(G?'SDD仕様書':'SDD specs'),
    '├── .devcontainer/    # '+(G?'開発環境':'Dev environment'),
    '├── roadmap/          # '+(G?'学習ロードマップ':'Learning roadmap'),
    '└── docs/             # '+(G?'ドキュメント':'Documents'));
  const dirNote=arch.pattern==='bff'?'\n> '+(G?'Note: Express のロジックは src/app/api/ 配下の Route Handlers に統合':'Note: Express logic integrated into src/app/api/ Route Handlers')+'\n':'';

  const entities=(a.data_entities||'users, items').split(/[,、]\s*/).map(e=>e.trim()).filter(Boolean);
  const entityLines=entities.map(en=>{
    const cols=getEntityColumns(en,G,entities);
    const lines=['### '+en,'- id: UUID (PK)'];
    cols.forEach(c=>lines.push('- '+c.col+': '+c.type+(c.constraint?' ('+c.constraint+')':'')+(c.desc?' — '+c.desc:'')));
    lines.push('- created_at: timestamp','- updated_at: timestamp');
    return lines.join('\n');
  }).join('\n\n');
  // B5: ER inference
  const er=inferER(a);
  const erRelSection=er.relationships.length?'\n'+(G?'### リレーション':'### Relationships')+'\n```\n'+er.relationships.join('\n')+'\n```':'';
  const erWarnSection=er.warnings.length?'\n'+(G?'### ⚠️ ドメイン適合性の注記':'### ⚠️ Domain Fit Notes')+'\n'+er.warnings.join('\n'):'';
  const supaNote=(arch.isBaaS&&be.includes('Supabase'))?'> '+(G?'Supabase Dashboard または supabase/migrations/ でスキーマ管理':'Manage schema via Supabase Dashboard or supabase/migrations/')+'\n\n':'';
  const deployNote=arch.pattern==='split'?' (FE) + Railway/Render ('+be+')':'';

  // Per-table RLS policies
  let rlsSection='';
  if(arch.isBaaS&&be.includes('Supabase')){
    const rlsLines=[G?'### RLS（Row Level Security）方針':'### RLS (Row Level Security) Policy',
      G?'全テーブルにRLS有効化。ポリシー例:':'Enable RLS on all tables. Policy examples:','','```sql'];
    (a.data_entities||'').split(/[,、]\s*/).map(e=>e.trim()).filter(Boolean).forEach(e=>{
      const en=e.trim();const tbl=pluralize(en);
      const cols=getEntityColumns(en,G,entities);
      const hasUserId=cols.some(c=>c.col==='user_id');
      const hasOwnerId=cols.some(c=>c.col==='owner_id'||c.col==='instructor_id'||c.col==='provider_id'||c.col==='sender_id');
      const ownerCol=hasUserId?'user_id':cols.find(c=>c.col==='owner_id'||c.col==='instructor_id'||c.col==='provider_id')?.col;
      if(en.toLowerCase()==='user'){
        rlsLines.push(`-- ${tbl}: ${G?'本人のみ読取・更新':'Owner read/update only'}`,
          `CREATE POLICY "${tbl}_select" ON ${tbl} FOR SELECT USING (auth.uid() = id);`,
          `CREATE POLICY "${tbl}_update" ON ${tbl} FOR UPDATE USING (auth.uid() = id);`,'');
      } else if(ownerCol){
        rlsLines.push(`-- ${tbl}: ${G?'本人のデータのみ操作可':'Owner CRUD only'}`,
          `CREATE POLICY "${tbl}_select" ON ${tbl} FOR SELECT USING (auth.uid() = ${ownerCol});`,
          `CREATE POLICY "${tbl}_insert" ON ${tbl} FOR INSERT WITH CHECK (auth.uid() = ${ownerCol});`,
          `CREATE POLICY "${tbl}_update" ON ${tbl} FOR UPDATE USING (auth.uid() = ${ownerCol});`,
          `CREATE POLICY "${tbl}_delete" ON ${tbl} FOR DELETE USING (auth.uid() = ${ownerCol});`,'');
      } else {
        rlsLines.push(`-- ${tbl}: ${G?'認証ユーザーは読取可':'Authenticated read'}`,
          `CREATE POLICY "${tbl}_select" ON ${tbl} FOR SELECT USING (auth.role() = 'authenticated');`,'');
      }
    });
    rlsLines.push('```');
    rlsSection='\n'+rlsLines.join('\n');
  }

  // Stripe integration section (uses hasPay/hasStripe from above)
  const hasStripe=hasPay&&(a.payment||'').includes('Stripe');
  let stripeSection='';
  if(hasStripe){
    const fn=arch.isBaaS&&be.includes('Supabase')?'Supabase Edge Function':'API Route';
    stripeSection='\n\n'+(G?'## 7. 決済設計 (Stripe)':'## 7. Payment Design (Stripe)')+'\n\n'+
      (G?'### サブスクリプションモデル':'### Subscription Model')+'\n'+
      '| '+(G?'プラン':'Plan')+' | '+(G?'価格':'Price')+' | '+(G?'機能制限':'Limits')+' |\n'+
      '|------|------|------|\n'+
      '| Free | ¥0 | '+(G?'基本機能のみ':'Basic features only')+' |\n'+
      '| Pro | ¥980/'+(G?'月':'mo')+' | '+(G?'全機能+優先サポート':'All features + priority support')+' |\n'+
      '| Enterprise | ¥9,800/'+(G?'月':'mo')+' | '+(G?'全機能+SLA+専用サポート':'All features + SLA + dedicated support')+' |\n\n'+
      (G?'### Webhook処理フロー':'### Webhook Flow')+'\n```\n'+
      'Stripe → POST /api/webhook/stripe → '+(G?'署名検証':'Verify signature')+'\n'+
      '  ├── invoice.paid → subscription.status = active\n'+
      '  ├── invoice.payment_failed → '+(G?'リトライ通知メール':'Retry notification email')+'\n'+
      '  ├── customer.subscription.deleted → subscription.status = canceled\n'+
      '  └── customer.subscription.updated → '+(G?'プラン変更反映':'Update plan info')+'\n```\n\n'+
      (G?'### DB設計':'### DB Design')+'\n'+
      (G?'subscriptions テーブル:':'subscriptions table:')+'\n'+
      '- user_id: UUID (FK → users)\n'+
      '- stripe_subscription_id: TEXT (UNIQUE)\n'+
      '- stripe_customer_id: TEXT\n'+
      '- status: active | canceled | past_due | trialing\n'+
      '- plan: free | pro | enterprise\n'+
      '- current_period_end: TIMESTAMP\n\n'+
      (G?'### 実装場所':'### Implementation')+': '+fn+'\n'+
      '- POST /api/checkout → stripe.checkout.sessions.create()\n'+
      '- POST /api/webhook/stripe → '+(G?'イベント処理':'Event handling')+'\n'+
      '- GET /api/subscription → '+(G?'現在のプラン取得':'Get current plan');
  }

  const fullEntitySection=supaNote+entityLines+erRelSection+erWarnSection+rlsSection;

  // ════ Technical Plan ════
  S.files['.spec/technical-plan.md']=[
    '# '+pn+' — '+(G?'技術計画書 (Technical Plan)':'Technical Plan'),
    '> Generated by DevForge v9 — '+date,'',
    G?'## 1. アーキテクチャ概要':'## 1. Architecture Overview',
    (G?'### パターン':'### Pattern')+': '+archLabel,'','```',arch.diagram,'```',
    arch.note?'\n> '+arch.note+'\n':'',
    G?'## 2. ディレクトリ構造':'## 2. Directory Structure','```',dirLines.join('\n'),'```',dirNote,'',
    G?'## 3. データベース設計':'## 3. Database Design',fullEntitySection,'',
    G?'## 4. 認証設計':'## 4. Auth Design',
    '- '+(G?'認証SoT':'Auth SoT')+': **'+auth.sot+'**',
    '- '+(G?'トークン':'Token')+': '+auth.tokenType,
    '- '+(G?'検証方法':'Verification')+': '+auth.tokenVerify,
    auth.social.length?'- '+(G?'対応プロバイダ':'Providers')+': '+auth.social.join(', '):'','',
    (()=>{
      var isMultiTenant=/マルチ|multi|RLS|組織|org.*hier/i.test((a.org_model||'')+(a.mvp_features||''));
      if(!isMultiTenant) return '';
      return [
        G?'## 4.5 マルチテナントアーキテクチャ':'## 4.5 Multi-Tenant Architecture',
        G?'### テナント分離戦略: Row-Level Security (RLS)':'### Tenant Isolation: Row-Level Security (RLS)',
        '```mermaid\ngraph LR\n  U[User]-->|auth.uid()|R[RLS Policy]\n  R-->|org_id check|T['+pn+' Data]\n  R-->|blocked|X[Other Org Data]\n  style R fill:#4f46e5,color:#fff\n```',
        '',
        G?'### 権限モデル (4階層)':'### Permission Model (4-tier)',
        '| Role | '+( G?'権限':'Permissions')+' |',
        '|------|-------------|',
        '| owner | '+( G?'全権限 (削除・課金含む)':'Full access (delete, billing)') +' |',
        '| admin | '+(G?'メンバー管理・設定変更':'Member mgmt, config changes')+' |',
        '| member | '+(G?'コンテンツ作成・編集':'Create/edit content')+' |',
        '| viewer | '+(G?'読み込みのみ':'Read only')+' |',
        '',
        G?'### データパーティション方針':'### Data Partitioning',
        '- '+( G?'全テーブルに `org_id` カラム必須':'All tables require `org_id` column'),
        '- '+(G?'クロステナントクエリ防止: RLSポリシーで強制':'Cross-tenant prevention: enforced by RLS'),
        '- '+(G?'インデックス: `(org_id, id)` 複合インデックス推奨':'Index: composite `(org_id, id)` recommended'),
        G?'> 詳細: `docs/73_enterprise_architecture.md`':
          '> Details: `docs/73_enterprise_architecture.md`'
      ].join('\n');
    })(),
    G?'## 5. 開発環境':'## 5. Dev Environment',
    '- Docker DevContainer (.devcontainer/)',
    '- '+(arch.isBaaS?be+' CLI (local emulator)':'Node.js LTS + '+db),
    '- '+((a.ai_tools||'Cursor').split(', ')[0])+' + '+(G?'AI支援':'AI-assisted'),'',
    '## 6. CI/CD','- GitHub Actions','- lint → test → build → deploy',
    '- '+(G?'デプロイ先':'Deploy')+': '+(a.deploy||'Vercel')+deployNote,
    stripeSection,''
  ].join('\n');

  // B7: Tasks from single schedule source
  const sprintTasks=(si)=>{
    if(si===0) return ['- [ ] '+(G?'リポジトリ作成・初期設定':'Repo init & config'),
      '- [ ] '+(G?'DevContainer設定':'DevContainer setup'),
      '- [ ] '+(G?'CI/CD パイプライン構築':'CI/CD pipeline'),
      '- [ ] '+(G?'データベーススキーマ定義':'Database schema')+((arch.isBaaS&&be.includes('Supabase'))?' + '+(G?'RLSポリシー設定':'RLS policy setup'):''),
      '- [ ] '+(G?'認証基盤実装':'Auth implementation')+' ('+auth.sot+')'].join('\n');
    if(si===1) return (a.mvp_features||(G?'CRUD操作':'CRUD Operations')).split(', ').map(f=>'- [ ] '+f).join('\n');
    if(si===2) return (a.screens||(G?'ダッシュボード, ログイン':'Dashboard, Login')).split(', ').map(s=>'- [ ] '+s+' '+(G?'画面実装':'screen')).join('\n');
    if(si===3) return ['- [ ] '+(G?'ユニットテスト (カバレッジ80%+)':'Unit tests (80%+ coverage)'),
      '- [ ] '+(G?'E2Eテスト (主要フロー)':'E2E tests (key flows)'),
      '- [ ] '+(G?'パフォーマンス最適化':'Performance optimization'),
      '- [ ] '+(G?'本番デプロイ':'Production deploy'),
      '- [ ] '+(G?'ドキュメント整備':'Documentation')].join('\n');
    if(si===4) return ['- [ ] '+a.mobile+' '+(G?'プロジェクト初期化':'project init'),
      '- [ ] '+(G?'画面実装（モバイル版）':'Mobile screens'),
      '- [ ] '+(G?'ストアビルド設定':'Store build config'),
      '- [ ] '+(G?'テスト':'Testing')].join('\n');
    return '';
  };

  S.files['.spec/tasks.md']=[
    '# '+pn+' — '+(G?'タスク一覧 (Tasks)':'Task List'),
    '> Generated by DevForge v9 — '+date,
    '> '+(G?'計画期間':'Timeline')+': '+sched.totalWeeks+' '+(G?'週間':'weeks')+' ('+sched.startDate+' 〜)','',
    ...sched.sprints.map((sp,i)=>'## '+sp.name+': '+(G?sp.focus_ja:sp.focus_en)+' ['+sp.weeks+']\n'+sprintTasks(i)),''
  ].join('\n\n');

  // ════ Verification ════
  const mobTest=hasMob?'| '+(G?'モバイルE2E':'Mobile E2E')+' | Maestro / Detox | '+(G?'主要フロー':'Key flows')+' |':'';
  const rlsTest=(arch.isBaaS&&be.includes('Supabase'))?'- [ ] '+(G?'RLSポリシーテスト (全テーブル)':'RLS policy tests (all tables)'):'';
  const features=(a.mvp_features||'').split(', ').filter(Boolean);

  S.files['.spec/verification.md']=[
    '# '+pn+' — '+(G?'検証計画書 (Verification)':'Verification Plan'),
    '> Generated by DevForge v9 — '+date,'',
    G?'## 1. テスト戦略':'## 1. Test Strategy',
    '| '+(G?'テスト種別':'Test Type')+' | '+(G?'ツール':'Tool')+' | '+(G?'カバレッジ目標':'Coverage Goal')+' |',
    '|-----------|--------|-------------|',
    '| '+(G?'ユニットテスト':'Unit Test')+' | Vitest | 80% |',
    '| '+(G?'統合テスト':'Integration')+' | Vitest | '+(G?'主要API全て':'All major APIs')+' |',
    '| '+(G?'E2Eテスト':'E2E Test')+' | Playwright | '+(G?'主要フロー':'Key flows')+' |',
    mobTest,'',
    G?'## 2. 駆動開発手法による検証':'## 2. Dev Method Verification',
    methods.map(m=>'### '+m+'\n- '+(G?'実施タイミング: 全Sprint':'Timing: All sprints')+'\n- '+(G?'検証項目: 仕様との整合性':'Verify: Spec alignment')).join('\n\n'),'',
    G?'## 3. パフォーマンス基準':'## 3. Performance Benchmarks',
    '- Lighthouse Score: 90+','- LCP: < 2.5s','- FID: < 100ms','- CLS: < 0.1','',
    G?'## 4. セキュリティチェック':'## 4. Security Checklist',
    '- [ ] '+(G?'OWASP Top 10対策確認':'OWASP Top 10 compliance'),
    '- [ ] '+(G?'依存パッケージ脆弱性スキャン':'Dependency vulnerability scan'),
    '- [ ] '+(G?'認証・認可テスト':'Auth/authorization tests')+' ('+auth.sot+')',
    '- [ ] '+(G?'データバリデーション確認':'Data validation check'),
    rlsTest,'',
    // G4: Feature-specific verification checklist
    G?'## 5. 機能別検証チェックリスト':'## 5. Feature Verification Checklist',
    ...features.flatMap(f=>{
      const fd=getFeatureDetail(f);
      if(!fd) return ['### '+f,'- [ ] '+(G?'実装完了':'Implementation done'),'- [ ] '+(G?'ユニットテスト通過':'Unit tests passing'),''];
      const criteria=(G?fd.criteria_ja:fd.criteria_en).map(c=>c.replace(/\{auth\}/g,a.auth||'OAuth'));
      return ['### '+f,...criteria.map(c=>'- [ ] '+c),''];
    }),
  ].join('\n');
}

