/* ── Pillar ⑦ Roadmap (9 files) — uses GT (gen-templates.js) — Phase B ── */
function genPillar7_Roadmap(a,pn){
  const T=k=>(GT[S.genLang]||GT.en)[k]||GT.en[k]||k;
  const level=a.skill_level||'Intermediate';const goal=a.learning_goal||(S.genLang==='ja'?'6ヶ月標準':'6-month standard');
  const fe=a.frontend||'React + Next.js';const be=a.backend||'Node.js + Express';
  const mob=a.mobile||T('none');const ai=a.ai_auto||T('none');const pay=a.payment||T('none');
  const noMob=mob===GT.ja.none||mob===GT.en.none;const noAI=ai===GT.ja.none||ai===GT.en.none;const noPay=pay===GT.ja.none||pay===GT.en.none;
  const isB=level.includes('Beginner');const isP=level.includes('Professional');
  const _auth=resolveAuth(a);const _arch=resolveArch(a);
  const _orm=_arch.isBaaS?(be.includes('Supabase')?'Supabase Client':be.includes('Firebase')?'Firebase SDK':'Convex'):!a.orm||a.orm.includes('Prisma')?'Prisma ORM':a.orm.includes('Drizzle')?'Drizzle ORM':a.orm.includes('TypeORM')?'TypeORM':a.orm.includes('SQLAlchemy')?'SQLAlchemy':a.orm.includes('Kysely')?'Kysely':'Prisma ORM';
  const months=goal.includes('3')?3:goal.includes('12')?12:6;
  const slug=pn.toLowerCase().replace(/[^a-z0-9]/g,'-');

  /* ── 1. LEARNING_PATH.md ── */
  const lpath=a.learning_path||'';
  S.files['roadmap/LEARNING_PATH.md']=`# ${pn} — ${T('lp_title')}
> ${T('lp_skill')}: ${level} | ${T('lp_target')}: ${goal}${lpath?' | '+T('lp_path')+': '+lpath:''} | Generated by DevForge v9

## Layer 1: ${T('l1')} ${isB?'[Month 1-2]':'[Week 1-2]'}
${isB?`- [ ] ${T('html5b')}\n- [ ] ${T('css3b')}\n- [ ] ${T('jsb')}`:`- [ ] ${T('tsAdv')}\n- [ ] ${T('cssAdv')}`}

## Layer 2: ${T('l2')} [${isB?'Month 3-4':'Month 1-2'}]
- [ ] ${fe} ${T('setup')}
- [ ] Tailwind CSS + shadcn/ui
- [ ] ${T('stMgmt')} (Zustand/Redux)
- [ ] React Query (${T('dataFetch')})
- [ ] ${T('testing')} (Vitest + Playwright)

## Layer 3: ${T('l3')} [${isB?'Month 5-6':'Month 2-3'}]
- [ ] ${be} ${T('setup')}
- [ ] ${T('dbDesign')} + ${_orm}
- [ ] REST API / GraphQL
- [ ] ${T('auth')} (${_auth.sot})
${!noMob?`\n## Layer 3.5: ${T('l3m')} [Month ${isB?7:4}-${isB?8:5}]\n- [ ] ${mob} ${T('mobEnv')}\n- [ ] ${T('mobNav')}\n- [ ] ${T('mobNative')}\n- [ ] ${T('mobStore')}\n`:''}
## Layer 4: DevOps [${isB?'Month '+(noMob?7:9):'Month '+(noMob?4:6)}]
- [ ] Docker + DevContainer
- [ ] GitHub Actions CI/CD
- [ ] ${a.deploy||'Vercel'} ${T('deploy')}
- [ ] ${T('monitor')}

## Layer 5: ${T('l5')} [${isB?'Month '+(noMob?8:10):'Month '+(noMob?5:7)}]
- [ ] ${(a.ai_tools||'Cursor').split(', ')[0]} ${T('aiUse')}
- [ ] ${T('mcpCfg')}
- [ ] ${T('aiOpt')}
${!noAI?`- [ ] ${ai} ${T('practice')}\n`:''}${!noPay?`\n## Layer 6: ${T('l6')} [Month ${months-1}-${months}]\n- [ ] ${pay}\n- [ ] ${T('billing')}\n- [ ] ${T('opsScale')}\n`:''}
## Layer 7: ${T('l7')} [${T('l7span')}]
${(a.dev_methods||'TDD').split(', ').map(m=>'- [ ] '+m+' '+T('practice')).join('\n')}
${a.future_features?`\n## ${T('ff_title')} [${T('ff_span')}]\n${a.future_features.split(', ').map((f,i)=>'- [ ] Phase '+(i<2?2:3)+': '+f+' — '+T('ff_integrate')).join('\n')}\n`:''}`;


  /* ── 2. TECH_STACK_GUIDE.md ── */
  const feR=fe.includes('Next')?T('nextR'):fe.includes('Vue')?T('vueR'):T('feGenR');
  const beR=be.includes('Supabase')?T('supaR'):be.includes('Express')?T('expR'):be.includes('NestJS')?T('nestR'):T('beGenR');
  const dbVal=a.database||'PostgreSQL';
  const dbR=dbVal.includes('Postgre')?T('pgR'):T('dbGenR');
  const dpVal=a.deploy||'Vercel';
  const dpR=dpVal.includes('Vercel')?T('vercelR'):T('deployGenR');

  S.files['roadmap/TECH_STACK_GUIDE.md']=`# ${pn} — ${T('ts_title')}
> Generated by DevForge v9

## ${T('ts_selected')}
| ${T('cat')} | ${T('tech')} | ${T('rationale')} |
|---------|------|------|
| ${T('feLabel')} | ${fe} | ${feR} |
| ${T('beLabel')} | ${be} | ${beR} |
| ${T('dbLabel')} | ${dbVal} | ${dbR} |
| ${T('deployLabel')} | ${dpVal} | ${dpR} |
${!noMob?`| ${T('mobileLabel')} | ${mob} | ${mob.includes('Expo')?T('expoR'):T('mobGenR')} |\n`:''}${!noPay?`| ${T('payLabel')} | ${pay} | ${T('payR')} |\n`:''}
## ${T('ts_deps')}
\`\`\`
${fe} ←→ ${be} ←→ ${dbVal}
  ↓           ↓
Tailwind    ${_orm}
  ↓           ↓
shadcn/ui   ${dpVal}
\`\`\`

## ${T('ts_versions')}
- Node.js: 22 LTS
- React: 19+
- Next.js: 15+
- TypeScript: 5.7+
- ${_orm}: ${_arch.isBaaS?"SDK latest":"6+"}
`;

  /* ── 3. MOBILE_GUIDE.md ── */
  S.files['roadmap/MOBILE_GUIDE.md']=!noMob?`# ${pn} — ${T('mob_title')}
> ${mob} | Generated by DevForge v9

## ${T('mob_env')}
\`\`\`bash
npx create-expo-app ${slug}-mobile --template blank-typescript
cd ${slug}-mobile
npx expo install expo-router expo-camera expo-notifications
\`\`\`

## ${T('mob_dir')}
\`\`\`
app/
├── (tabs)/
│   ├── index.tsx       # ${T('mob_home')}
│   ├── explore.tsx     # ${T('mob_explore')}
│   └── profile.tsx     # ${T('mob_profile')}
├── _layout.tsx         # ${T('mob_root')}
└── +not-found.tsx      # 404
\`\`\`

## EAS Build${T('mob_eas')}
\`\`\`json
{ "build": { "production": { "distribution": "store" }, "preview": { "distribution": "internal" } } }
\`\`\`

## ${T('mob_libs')}
- NativeWind (Tailwind for RN)
- React Native Reanimated (${T('mob_anim')})
- FlashList (${T('mob_list')})
- Expo Image (${T('mob_img')})
`:`# ${T('mob_title')}\n\n${T('mob_none')}`;

  /* ── 4. TOOLS_SETUP.md ── */
  const aiTools=(a.ai_tools||'Cursor').split(', ');
  const toolLines=aiTools.map(t=>`- **${t}**: ${t==='Cursor'?'https://cursor.sh/':t.includes('Antigravity')?'https://antigravity.google/':t.includes('Claude')?'Claude Code CLI: npm install -g @anthropic-ai/claude-code':t.includes('Aider')?'pip install aider-chat (BYOK)':t.includes('Amazon Q')?T('tool_vsInst')+' / aws.amazon.com/q/developer/':t.includes('Augment')?T('tool_vsInst')+' / augmentcode.com':t.includes('Tabnine')?T('tool_vsInst')+' / tabnine.com':t.includes('OpenRouter')?'https://openrouter.ai/ (API key)':t.includes('Copilot')?T('tool_vsInst'):T('tool_official')}`).join('\n');

  S.files['roadmap/TOOLS_SETUP.md']=`# ${pn} — ${T('tool_title')}
> Generated by DevForge v9

## 1. ${T('tool_essential')}
\`\`\`bash
# Node.js (${T('tool_rec')}: v22 LTS)
# https://nodejs.org/

# ${T('tool_pkgmgr')}
npm install -g pnpm

# ${T('tool_init')}
pnpm create next-app ${slug} --typescript --tailwind --eslint

# ${T('tool_docker')}
docker compose up -d
\`\`\`

## 2. ${T('tool_ai')}
${toolLines}

## 3. VS Code ${T('tool_ext')}
- ESLint, Prettier, Tailwind CSS IntelliSense
- ${_arch.isBaaS?(be.includes("Supabase")?"supabase.supabase-vscode":"ms-azuretools.vscode-azurefunctions"):"prisma.prisma"}, GitLens, Error Lens
- GitHub Copilot (${T('tool_used')})

## 4. ${T('tool_env')} (.env.example)
\`\`\`
DATABASE_URL="postgresql://dev:devpass@localhost:5432/${slug.replace(/-/g,'_')}"
NEXTAUTH_SECRET="your-secret-here"
NEXTAUTH_URL="http://localhost:3000"
${pay.includes('Stripe')?'STRIPE_SECRET_KEY="sk_test_..."\nSTRIPE_PUBLISHABLE_KEY="pk_test_..."\nSTRIPE_WEBHOOK_SECRET="whsec_..."':''}
\`\`\`
`;

  /* ── 5. RESOURCES.md ── */
  S.files['roadmap/RESOURCES.md']=`# ${pn} — ${T('res_title')}
> Generated by DevForge v9

## ${T('res_official')}
${fe.includes('React')?'- [React](https://react.dev/)\n- [Next.js](https://nextjs.org/docs)':''}
${fe.includes('Vue')?'- [Vue 3](https://vuejs.org/)\n- [Nuxt](https://nuxt.com/)':''}
${be.includes('Node')?'- [Node.js](https://nodejs.org/docs/)':''}
${be.includes('Supabase')?'- [Supabase](https://supabase.com/docs)':''}
- [TypeScript](https://www.typescriptlang.org/docs/)
- [Tailwind CSS](https://tailwindcss.com/docs)
- [${_orm}](${_arch.isBaaS?(be.includes("Supabase")?"https://supabase.com/docs":"https://firebase.google.com/docs"):"https://www.prisma.io/docs"})

## ${T('res_ai')}
- [CLAUDE.md ${T('res_bp')}](https://docs.anthropic.com/)
- [Cursor ${T('res_docs')}](https://docs.cursor.com/)
- [MCP ${T('res_proto')}](https://modelcontextprotocol.io/)
${!noAI?`- [Vibe Coding ${T('res_patterns')}](https://vibecoding.dev/)`:''}\

## ${T('res_books')}
- "${T('res_fullstack')}" (${isB?T('res_beg'):T('res_int')})
- "${T('res_tsPractice')}"
- "${(a.dev_methods||'TDD').split(', ')[0]}${T('res_design')}"
${!noPay?`- "${T('res_saas')}"\n- "${T('res_headless')}"`:''}\
`;

  /* ── 6. MILESTONES.md ── */
  const msLabels=T('ms_m');
  S.files['roadmap/MILESTONES.md']=`# ${pn} — ${T('ms_title')}
> ${T('ms_target')}: ${goal} | Generated by DevForge v9

${Array.from({length:months},(_,i)=>`## Month ${i+1}: ${(typeof msLabels==='object'?msLabels:GT.en.ms_m)[Math.min(i,6)]}
- [ ] ${T('ms_criteria')}
- [ ] ${T('ms_review')}
- [ ] ${T('ms_retro')}`).join('\n\n')}
`;

  /* ── 7. AI_WORKFLOW.md ── */
  S.files['roadmap/AI_WORKFLOW.md']=`# ${pn} — ${T('aiw_title')}
> Generated by DevForge v9

## ${T('aiw_flow')}
\`\`\`
1. ${T('aiw_s1')} → 2. ${T('aiw_s2')} → 3. ${T('aiw_s3')} → 4. ${T('aiw_s4')} → 5. ${T('aiw_s5')} → 6. ${T('aiw_s6')}
\`\`\`

## ${T('aiw_select')}
| ${T('aiw_task')} | ${T('aiw_rec')} | ${T('rationale')} |
|--------|-----------|------|
| ${T('aiw_newfile')} | ${aiTools[0]} | ${T('aiw_ctx')} |
| ${T('aiw_bugfix')} | Claude Code | ${T('aiw_term')} |
| ${T('aiw_testgen')} | GitHub Copilot | ${T('aiw_inline')} |
| ${T('aiw_refactor')} | Cursor | ${T('aiw_multi')} |

## ${T('aiw_mcp')}
1. **context7**: ${T('aiw_mcp1')}
2. **filesystem**: ${T('aiw_mcp2')}
3. **playwright**: ${T('aiw_mcp3')}

## ${T('aiw_prompt')}

### 1. ${T('aiw_addFeature')}
\`\`\`
${T('aiw_promptText')}
\`\`\`

### 2. ${T('aiw_bugfixPrompt')}
\`\`\`
${T('aiw_bugfixText')}
\`\`\`

### 3. ${T('aiw_refactorPrompt')}
\`\`\`
${T('aiw_refactorText')}
\`\`\`
`;

  /* ── 8. AI_AUTONOMOUS.md ── */
  const aiIsVibe=ai.includes('Vibe');const aiIsMulti=ai.includes('マルチ')||ai.includes('Multi');const aiIsFull=ai.includes('フル')||ai.includes('Full');
  S.files['roadmap/AI_AUTONOMOUS.md']=!noAI?`# ${pn} — ${T('aia_title')}
> ${T('aia_level')}: ${ai} | Generated by DevForge v9

## ${T('aia_vibe')}
${T('aia_vibeDesc')}

### ${T('aia_basic')}
1. **${T('aia_f1')}**: ${T('aia_f1ex')}
2. **${T('aia_f2')}**: ${T('aia_f2ex')}
3. **${T('aia_f3')}**: ${T('aia_f3ex')}
4. **${T('aia_f4')}**: ${T('aia_f4ex')}

### ${T('aia_tools')}
${aiIsVibe?`- ${T('aia_vibe1')}\n- ${T('aia_vibe2')}\n- ${T('aia_vibe3')}`:''}
${aiIsMulti?`- ${T('aia_multi1')}\n- ${T('aia_multi2')}\n- ${T('aia_multi3')}`:''}
${aiIsFull?`- ${T('aia_full1')}\n- ${T('aia_full2')}\n- ${T('aia_full3')}\n- ${T('aia_async1')}`:''}

### ${T('aia_bp')}
1. ${T('aia_bp1')}
2. ${T('aia_bp2')}
3. ${T('aia_bp3')}
4. ${T('aia_bp4')}
`:`# ${T('aia_title')}\n\n${T('aia_none')}${aiTools[0]}${T('aia_none2')}`;

  /* ── 9. SAAS_COMMERCE_GUIDE.md ── */
  S.files['roadmap/SAAS_COMMERCE_GUIDE.md']=!noPay?`# ${pn} — ${T('sc_title')}
> ${T('sc_selected')}: ${pay} | Generated by DevForge v9

## ${T('sc_compare')}
| ${T('sc_platform')} | ${T('sc_rate')} | MoR | ${T('sc_feat')} |
|---------------|------|-----|------|
| Stripe | 2.9%+30¢ | Beta | ${T('sc_stripe')} |
| Paddle | 5%+50¢ | ✅ | ${T('sc_paddle')} |
| Lemon Squeezy (Stripe) | 5%+50¢ | ✅ | ${T('sc_lemon')} |

${pay.includes('Stripe')?`## ${T('sc_impl')}
\`\`\`bash
npm install stripe @stripe/stripe-js
\`\`\`

### Checkout Session
\`\`\`typescript
import Stripe from 'stripe';
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!);
const session = await stripe.checkout.sessions.create({
  line_items: [{ price: 'price_xxx', quantity: 1 }],
  mode: 'subscription',
  success_url: '/success',
  cancel_url: '/cancel',
});
\`\`\`

### ${T('sc_webhook')}
\`\`\`typescript
// POST /api/webhooks/stripe
const event = stripe.webhooks.constructEvent(body, sig, secret);
switch(event.type) {
  case 'checkout.session.completed': // ${T('sc_paid')}
  case 'invoice.paid': // ${T('sc_renew')}
  case 'customer.subscription.deleted': // ${T('sc_cancel')}
}
\`\`\`
`:''}${pay.includes('CMS')?`## ${T('sc_cms')} (microCMS)
\`\`\`bash
npm install microcms-js-sdk
\`\`\`

\`\`\`typescript
import { createClient } from 'microcms-js-sdk';
const client = createClient({
  serviceDomain: 'your-domain',
  apiKey: process.env.MICROCMS_API_KEY!,
});
const data = await client.getList({ endpoint: 'articles' });
\`\`\`
`:''}${pay.includes('EC')?`## ${T('sc_ec')} (Medusa)
\`\`\`bash
npx create-medusa-app@latest
\`\`\`
- ${T('sc_prodMgmt')}: Admin Dashboard
- ${T('sc_payment')}: Stripe Plugin
- ${T('sc_ship')}: ${T('sc_fulfill')}
`:''}
`:`# ${T('sc_title')}\n\n${T('sc_none')}`;
}
